/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_art_storendk_model_Store */

#ifndef _Included_ru_art_storendk_model_Store
#define _Included_ru_art_storendk_model_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_art_storendk_model_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_art_storendk_model_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_art_storendk_model_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ru_art_storendk_model_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ru_art_storendk_model_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_art_storendk_model_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_art_storendk_model_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_art_storendk_model_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
